### ISSUE TITLE
Tracker for Release v1.0.0

### ISSUE THREAD

**Issue by phoenisx** [willofindie/vscode-cssvar#1]
### Minimal Basic Support

> Status: [DONE]

- [x] Show variable values in imported CSS Files, in Editor Line Bar.
  - This will help to get details on CSS Variable being used in different files.
- [x] Both the below changes require heavy changes. Will do it when I have time.
  - [x] ~~Add support for `var` to trigger the completion prompt.~~ _Not so important, will not support this._
  - [x] Intelligently add semicolon. Add only if the line does not contain any Semicolon.
    - This also includes cases like SASS variable declarations: `("white", $white, var(--grey800)),`
- [x] Fix: Filter Regex, to support variable triggers inside brackets. For eg. `var(--)`, this does not trigger the intellisense
- [x] Support JS/TS extensions as well. Eg. "var(--color)"
- [x] Support Theming, using theme classname. defaults to empty string "".
    - Eg. `body.dark {}` or `body.light {}` rules.
- [x] Support short extension names like `ts`, `tsx` as mentioned in #3 
- [x] Support glob pattern for files config.

### Advance Support

> Status: [Pending]

Below mentioned tasks require a complete re-write of the code, to support [Language Servers (LSP)](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide).

Reference for LSP support can be taken from [CSS Peek](https://github.com/pranaygp/vscode-css-peek/commit/dcb0dc75550701968653aeaa6adf6cecda159c3c)

- [ ] Make the variable control clickable, for the dev to redirect to it's source. To support this I will have to maintain the precedence order of each variable
    - Need support for - `DefinitionProvider`
- [x] ~~Show Error status (linting), if an unknown css variable is being used.~~
  - Since the plugin works with Global CSS Variables and locally defined CSS variables are not read, adding a linter
     without acknowledging local variables can have bad side-effects. Will not support this feature, unless I find
     some simpler solution for this.
- [ ] ~~Show only Color values from CSS variable, for all CSS `*color` properties, and for any non-color CSS properties (like `padding`) to show only other kinds of variables.~~
    - This should be made optional, as there might be users, who want to see all the variables in dropdown.
---
  
**Not Interested, just keeping a note of stuff:**
- Support SASS?? (Still unsure on this, as SASS/LESS etc. seems overrated now-a-days).

**Comment by phoenisx** [comment]
CSS Properties that have might have `<color>` as exact values _(Need to verify this for each anyways)_

```js
[
  "accent-color",
  "background-color",
  "border-block-color",
  "border-block-end-color",
  "border-block-start-color",
  "border-bottom-color",
  "border-color",
  "border-inline-color",
  "border-inline-end-color",
  "border-inline-start-color",
  "border-left-color",
  "border-right-color",
  "border-top-color",
  "caret-color",
  "color",
  "color-adjust",
  "color-interpolation-filters",
  "color-scheme",
  "column-rule-color",
  "fill-color",
  "flood-color",
  "forced-color-adjust",
  "lighting-color",
  "outline-color",
  "print-color-adjust",
  "scrollbar-color",
  "stroke-color",
  "text-decoration-color",
  "text-emphasis-color"
]
```

Other properties, may or may not contain `<color>` values. Thus, it's better to show all property names in suggestions, when current property been worked upon does not have a defined kind.

**Comment by phoenisx** [comment]
This checklist is done and released: https://github.com/willofindie/vscode-cssvar/releases/tag/v1.0.0
