### ISSUE TITLE
Support VSCode hover action on variables

### ISSUE THREAD

**Issue by phoenisx** [willofindie/vscode-cssvar#60]
Similar to TailwindCSS:

<img width="694" alt="image" src="https://user-images.githubusercontent.com/11786283/184526818-ebb94a87-dc85-46ef-877d-1398f960950b.png">

## TODO:

- [ ] Add a vscode setting `enableHover` to keep this feature optional.
- [ ] Should be available only for CSS variables.
- [ ] Should work with JS and CSS alike, point to right source value.

**Comment by phoenisx** [comment]
## TODO:

- Add a vscode setting `enableHover` to keep this feature optional.
- Should be available only for CSS variables.
- Should work with JS and CSS alike, point to right source value.
